### PR TITLE
List setuptools under install_requires

### PR DESCRIPTION
**Pull request by sbraz**
Hi,
pkg_resources is used, making setuptools a runtime dependency.

### CODE REVIEW

**Comment by graingert** [comment]
might be neater to use `from packaging.version import parse`

**Comment by sbraz** [comment]
> might be neater to use `from packaging.version import parse`

I don't have a strong opinion on that. As long as the new dependency is listed in `install_requires`.

**Review by glyph — APPROVED** [review]
Hi @sbraz,

Sorry for not getting to this sooner. Looks like the place dependencies have been specified has moved. Can you redo this for `setup.cfg` instead?  I think we can land it after that.

Thanks for your attention to detail.

**Comment by sbraz** [comment]
Hi, done. I wonder: wouldn't `packaging.version.parse` be a more modern alternative to `pkg_resource`'s `parse_version`?

**Review by graingert — APPROVED** [review]
Yeah packaging.version is the new blessed way. I'd love to see a PR to move to it

**Comment by adiroiban** [comment]
I guess that while `packaging.version` is added, there is nothing wrong with this PR and it can be merged.


I now see that the tests on travis-ci are not running... I guess it's time to move to GitHub actions

I will create a PR to move to github actions.

**Comment by adiroiban** [comment]
GHA migration available for review at https://github.com/twisted/incremental/pull/73

**Pull request merged**
