### PR TITLE
README: Fix badges

### PR DESCRIPTION
**Pull request by hugovk**
Before:

image

After:

image

### CODE REVIEW

**Comment by hugovk** [comment]
CI failure is unrelated to this change.

See https://github.com/twisted/incremental/pull/40 for a fix.

**Comment by hugovk** [comment]
Now #40 is merged I've rebased and this is now all green.

**Comment by glyph** [comment]
Thank you for your contribution, @hugovk !  Looks great, I'll land it.

**Comment by glyph** [comment]
Post landing:

image

**Pull request merged**
