### PR TITLE
Fold Eventually into Incremental

### PR DESCRIPTION
**Pull request by hawkowl**

### CODE REVIEW

**Comment by Julian** [comment]
Not sure how set we are on this already or if it counts for anything I'm -0.5 on merging these together. I think there's definitely value in having lots of small packages.

**Comment by glyph** [comment]
bump

**Comment by glyph** [comment]
@hawkowl @Julian How are we feeling about this after this long interlude? Should we just close the PR?

**Comment by hawkowl** [comment]
yes -- I think we need to have a bit more of a cohesive plan on these splitouts (since a lot of them depend on Failure and such anyway)

**Pull request closed without merging**
